#
# EcoQuests
# by Auxilor
#

quests:
  icon:
    line-wrap: 32
    lore:
      - '%description%'
      - ''
      - '<#c2beba>Tasks:'
      - ' %tasks%'
      - ''
      - '<#c2beba>Rewards:'
      - ' %rewards%'
      - ''
      - '%time_since%'
    name: <#eac8a3><b>%quest%
    click-to-start-lore:
      - ''
      - <white>ꑃ <yellow>Click to start!
  start:
    sound:
      volume: 1.0
      sound: entity_player_levelup
      pitch: 1.9
      category: player
      enabled: true
    message:
      message:
        - ' '
        - '<#eacda3><b>ɴᴇᴡ ǫᴜᴇꜱᴛ:'
        - ' <#a3c4ea>%quest%'
        - ' '
        - '<#eacda3><b>ʀᴇᴡᴀʀᴅꜱ:'
        - ' %rewards%'
        - ' '
      enabled: true
    title:
      fade-out: 0.5
      fade-in: 0.5
      subtitle: <#a3c4ea>%quest%
      title: <#eacda3><b>ɴᴇᴡ ǫᴜᴇꜱᴛ
      enabled: true
      stay: 2
  complete:
    sound:
      volume: 1.0
      sound: ui_toast_challenge_complete
      pitch: 1.5
      category: player
      enabled: true
    message:
      message:
        - ' '
        - '<#eacda3><b>ǫᴜᴇꜱᴛ ᴄᴏᴍᴘʟᴇᴛᴇ:'
        - ' <#a3c4ea>%quest%'
        - ' '
        - '<#eacda3><b>ʀᴇᴡᴀʀᴅꜱ:'
        - ' %rewards%'
        - ' '
      enabled: true
    title:
      fade-out: 0.5
      fade-in: 0.5
      subtitle: <#8be851>%quest%
      title: <#51e874><b>ǫᴜᴇꜱᴛ ᴄᴏᴍᴘʟᴇᴛᴇ
      enabled: true
      stay: 2
completed-gui:
  next-page:
    item: paper item_model:nexo:playtime_next name:"<yellow>Next Page"
    location:
      column: 6
      row: 6
  quest-area:
    bottom-right:
      column: 8
      row: 5
    top-left:
      column: 2
      row: 2
  back:
    item: paper item_model:nexo:empty
    location:
      column: 4
      row: 5
  custom-slots: []
  title: <shift:-18><glyph:quest2>
  rows: 6
  mask:
    materials: []
    pattern: []
  prev-page:
    item: paper item_model:nexo:playtime_previous name:"<yellow>Previous Page"
    location:
      column: 4
      row: 6
scan-interval: -1
gui:
  click-to-start: true
  next-page:
    item: paper item_model:nexo:playtime_next name:"<yellow>Next Page"
    location:
      column: 9
      row: 3
  quest-area:
    bottom-right:
      column: 8
      row: 5
    top-left:
      column: 6
      row: 2
  custom-slots: []
  quest-info:
    item: player_head item_model:nexo:2d_player_head_large
    lore:
      - ''
      - '<gray>ᴀᴄᴛɪᴠᴇ: <#a3c4ea>%ecoquests_quests_active% quests'
      - '<gray>ᴄᴏᴍᴘʟᴇᴛᴇ: <#a3c4ea>%ecoquests_quests_completed% quests'
    name: <#a3c4ea><b>Quest Book
    location:
      column: 2
      row: 2
  quest-info2:
    item: paper item_model:nexo:empty
    lore:
      - ''
      - '<gray>ᴀᴄᴛɪᴠᴇ: <#a3c4ea>%ecoquests_quests_active% quests'
      - '<gray>ᴄᴏᴍᴘʟᴇᴛᴇ: <#a3c4ea>%ecoquests_quests_completed% quests'
    name: <#a3c4ea><b>Quest Book
    location:
      column: 3
      row: 2
  quest-info3:
    item: paper item_model:nexo:empty
    lore:
      - ''
      - '<gray>ᴀᴄᴛɪᴠᴇ: <#a3c4ea>%ecoquests_quests_active% quests'
      - '<gray>ᴄᴏᴍᴘʟᴇᴛᴇ: <#a3c4ea>%ecoquests_quests_completed% quests'
    name: <#a3c4ea><b>Quest Book
    location:
      column: 2
      row: 3
  quest-info4:
    item: paper item_model:nexo:empty
    lore:
      - ''
      - '<gray>ᴀᴄᴛɪᴠᴇ: <#a3c4ea>%ecoquests_quests_active% quests'
      - '<gray>ᴄᴏᴍᴘʟᴇᴛᴇ: <#a3c4ea>%ecoquests_quests_completed% quests'
    name: <#a3c4ea><b>Quest Book
    location:
      column: 3
      row: 3
  title: <shift:-18><glyph:quest>
  rows: 6
  close:
    item: paper item_model:nexo:empty
    name: <red>Close
    location:
      column: 4
      row: 5
  mask:
    materials: []
    pattern: []
  prev-page:
    item: paper item_model:nexo:playtime_previous name:"<yellow>Previous Page"
    location:
      column: 1
      row: 3
tasks:
  completed: <white>ꐕ %description%
  not-completed: <white>ꐔ %description%
use-local-storage: false

